### ISSUE TITLE
Formato de documento

### ISSUE THREAD

**Issue by solmos** [PaulaMorBla14/TFG-Baloncesto#2]
¿Tienes pensado entregar el trabajo en un archivo HTML?

https://github.com/PaulaMorBla14/TFG-Baloncesto/blob/e706cf14d27adceebf21ec3934363fb9cce801ed/Project_v1.Rmd#L6

No sé si se acepta este formato. Yo diría que sería conveniente exportarlo a PDF.

Además, puedes exportarlo también a GitHub Flavour Markdown para que lo podamos leer de una forma más visual en el propio GitHub.

Para ello añade las siguientes líneas a la sección YAML de tu documento:

```yaml
output:
  pdf_document: default
  github_document: default
```

Y dale a Knit en el formato apropiado.
